import 'package:who_goes_first/rule.dart';
import "dart:math";

class Rules {
  static final Random _random = Random();

  static Rule random() => rules[_random.nextInt(rules.length)];

  static List<Rule> rules = [
    Rule(rule: "Who has the pointiest ears?", games: ["Small World"]),
    Rule(rule: "Who owns the biggest house?", games: ["For Sale"]),
    Rule(rule: "Who has had the worst day?", games: ["Gloom"]),
    Rule(rule: "Who is the most well traveled?", games: ["Ticket to Ride"]),
    Rule(rule: "Who is wearing the most colorful clothes?", games: ["Hanabi", "Flowerpower", "Match of the Penguins"]),
    Rule(rule: "Who has the longest beard?", games: ["Once Upon a Time", "Dwarven Dig!"]),
    Rule(rule: "Who does the youngest player choose?", games: ["Carcassonne"]),
    Rule(rule: "Who can stand on one leg the longest?", games: ["Animal upon Animal"]),
    Rule(rule: "Who is the cattiest player?", games: ["Kittens in a Blender"]),
    Rule(rule: "Who is the thirstiest?", games: ["Forbidden Desert"]),
    Rule(rule: "Who last visited an island?", games: ["Forbidden Island", "Maka Baka"]),
    Rule(rule: "Who got up the earliest this morning?", games: ["Smash Up!"]),
    Rule(rule: "Who most recently went on a date?", games: ["Love Letter"]),
    Rule(rule: "Who has the best maniacal laugh?", games: ["Mad Scientist University", "IGOR: The Mad Scientist’s Lament"]),
    Rule(rule: "Who is wearing the most green?", games: ["Kodama: The Tree Spirits", "Batt'l Kha'os"]),
    Rule(rule: "Who has the longest hair?", games: ["Monkeys on the Moon", "Aquarius"]),
    Rule(rule: "Who dug a garden last?", games: ["Terra Mystica"]),
    Rule(rule: "Who looks most like a pirate?", games: ["Cartagena", "Pirates vs Dinosaurs", "Oath of the Brotherhood"]),
    Rule(rule: "Who owns the game?", games: ["Sucking Vacuum", "Junta", "Neuroshima Hex!"]),
    Rule(rule: "Who is the nicest?", games: ["Dungeon Lords"]),
    Rule(rule: "Who has read the most sci-fi?", games: ["Android"]),
    Rule(rule: "Who looks most like a monster?", games: ["Fearsome Floors"]),
    Rule(rule: "Who has the best story about being stranded?", games: ["Lift Off: Get Me Off This Planet"]),
    Rule(rule: "Who has most recently been on a boat?", games: ["Harbour"]),
    Rule(rule: "Who is the hungriest?", games: ["Mamma Mia!", "Guts of Glory"]),
    Rule(rule: "Who can do the best monkey impression?", games: ["Too Many Monkeys", "Coco Crazy"]),
    Rule(rule: "Who has the nicest jewelry?", games: ["Queen's Necklace"]),
    Rule(rule: "Who is the tallest?", games: ["Takenoko", "Campanile"]),
    Rule(rule: "Without looking at a clock, who can guess what time it is?", games: ["Chrononauts"]),
    Rule(rule: "Who has the most cash on them?", games: ["Corporate America", "Sheriff of Nottingham", "Martian 12s"]),
    Rule(rule: "Who has most recently visited London?", games: ["Great Fire of London 1666", "Portobello Market"]),
    Rule(rule: "Who has most recently been on a train?", games: ["Trains"]),
    Rule(rule: "Who has most recently visited another city?", games: ["Lords of Waterdeep"]),
    Rule(rule: "Who has most recently flipped a table?", games: ["Flip City"]),
    Rule(rule: "Who has most recently bought or sold something?", games: ["Mercante"]),
    Rule(rule: "Who has most recently visited a forest?", games: ["Lagoon"]),
    Rule(rule: "Who lives closest to water?", games: ["Le Havre"]),
    Rule(rule: "Who last visited a mountain?", games: ["K2"]),
    Rule(rule: "Who looks the shiftiest?", games: ["Spyfall"]),
    Rule(rule: "Who last went on a cruise?", games: ["Atlantic Star"]),
    Rule(rule: "Who has most recently traded stock?", games: ["The Motley Fool's: Buy Low Sell High"]),
    Rule(rule: "Who was the last person to have a haircut?", games: ["Shear Panic!"]),
    Rule(rule: "Who is the shortest?", games: ["The Conquest of Space"]),
    Rule(rule: "Who has the snazziest pants?", games: ["Who Stole Ed’s Pants?"]),
    Rule(rule: "Who is the last person to laugh?", games: ["Gheos"]),
    Rule(rule: "Who is ready to go first and takes the starting action?", games: ["Fluxx", "Dixit", "Dixit Odyssey", "Galaxy Truckers"]),
    Rule(rule: "Who broke the law most recently?", games: ["Grifters"]),
    Rule(rule: "Who most recently bought justice to the world?", games: ["Love Letter: Batman"]),
    Rule(rule: "Who made tea most recently?", games: ["Hanamikoji"]),
    Rule(rule: "Who looks most like a zombie?", games: ["City of Horror"]),
    Rule(rule: "Who has the squarest shaped head?", games: ["Cube Quest"]),
    Rule(rule: "Who has eaten nuts most recently?", games: ["Nuts!"]),
    Rule(rule: "Who can say 'brraaains' with the most zombie-like feeling?", games: ["Zombie Dice"]),
    Rule(rule: "Who has brought the most snacks?", games: ["Dragon Farkle"]),
    Rule(rule: "Who last watered a plant?", games: ["Arboretum"]),
    Rule(rule: "Who can cackle the most like a vile and greedy medieval pardoner?", games: ["The Road to Canterbury"]),
    Rule(rule: "Who has the most tattoos?", games: ["Camp Grizzly"]),
    Rule(rule: "Who most recently read a novel?", games: ["Paperback"]),
    Rule(rule: "Who visited a cathedral most recently?", games: ["The Pillars of the Earth"]),
    Rule(rule: "Who last played a train game?", games: ["Cleopatra’s Caboose"]),
    Rule(rule: "Who looks most like an alien?", games: ["Andromeda"]),
    Rule(rule: "Who most recently put their feet in sand?", games: ["Archaeology: The New Expedition"]),
    Rule(rule: "Who last ate mushrooms?", games: ["Morels"]),
    Rule(rule: "Who has the longest whiskers?", games: ["Hot Tin Roof"]),
    Rule(rule: "Who has the watch furthest backwards in time?", games: ["Legacy: Gears of Time"]),
    Rule(rule: "Who is the wisest?", games: ["Himalaya", "The Bridges of Shangri-La"]),
    Rule(rule: "Who is the hairiest?", games: ["Mammoth Hunters", "Monkey Arena"]),
    Rule(rule: "Who has been deepest down in the sea?", games: ["Nautilus"]),
    Rule(rule: "Who can shout “Olé!” the loudest?", games: ["Salamanca"]),
    Rule(rule: "Who can do the best penguin impression?", games: ["Penguin Soccer"]),
    Rule(rule: "Who suggested the game?", games: ["GUBS: A Game of Wit and Luck", "Roads and Boats"]),
    Rule(rule: "Who is wearing the most black?", games: ["Ice Pirates of Harbour Grace"]),
    Rule(rule: "Who is the least wise?", games: [""]),
    Rule(rule: "Who has the tiniest teeth?", games: ["Mäuse-Rallye"]),
    Rule(rule: "Who can hold a high C note for the longest?", games: ["Maestro"]),
    Rule(rule: "Who is most in need of a shave?", games: ["Goldrush-City"]),
    Rule(rule: "Who has the largest cowboy boots?", games: ["Abilene"]),
    Rule(rule: "Who is the dirtiest?", games: ["Neolithibum"]),
    Rule(rule: "Who can hold their breath underwater for the longest?", games: ["The Reef"]),
    Rule(rule: "Who most recently visited Italy?", games: ["La Cittá"]),
    Rule(rule: "Who has the hardest look in their eyes?", games: ["Saloon"]),
    Rule(rule: "Who is wearing the most jewelry?", games: ["Das Kollier"]),
    Rule(rule: "Who has their alarm set for the earliest time?", games: ["Counting Zzzzs"]),
    Rule(rule: "Who is the quickest person to wave the highest denomination banknote or who bought a welding torch?", games: ["Safeknacker"]),
    Rule(rule: "Who can jump the highest?", games: ["Dancing Eggs"]),
    Rule(rule: "Who most recently ate Greek food?", games: ["Hera and Zeus"]),
    Rule(rule: "Who can point to the North the fastest?", games: ["Discovery"]),
    Rule(rule: "Who owns the most railway games?", games: ["Railroad Dice: The First Rails"]),
    Rule(rule: "Who has seen the most Kim Possible episodes?", games: ["Kim Possible Game"]),
    Rule(rule: "Who last saw a mammoth?", games: ["Stone Age"]),
    Rule(rule: "Who lives closest to Venice?", games: ["Oltre Mare"]),
    Rule(rule: "Who is the most afraid of water?", games: ["Niagara"]),
    Rule(rule: "Who bought the oldest object with them?", games: ["Jenseits von Theben"]),
    Rule(rule: "Who has the biggest hands?", games: ["The Mole in the Hole"]),
    Rule(rule: "Who is the most sea-worthy player?", games: ["Tonga Bongo"]),
    Rule(rule: "Who has most recently stroked a sheep?", games: ["Herd the Sheep"]),
    Rule(rule: "Who thinks they know the most about Australia?", games: ["Australia"]),
    Rule(rule: "Who got up the latest today?", games: ["Dawn Under"]),
    Rule(rule: "Who most recently achieved a waypoint in life?", games: ["Tempus"]),
    Rule(rule: "Who has most recently visited a real Castle?", games: ["Château Roquefort"]),
    Rule(rule: "Who has the longest ears?", games: ["Hoppladi, Hopplada!"]),
    Rule(rule: "Who has the longest neck?", games: ["Savannah Tails"]),
    Rule(rule: "Who can 'moo' the loudest?", games: ["Black Sheep"]),
    Rule(rule: "Who looks most like a moose?", games: ["Bunny Bunny Moose Moose"]),
    Rule(rule: "Who has the freshest breath?", games: ["Mint Works"]),
    Rule(rule: "Who has their birthday next?", games: ["Seasons: The Calendar Rummy Game", "The Stars are Right"]),
    Rule(rule: "Who can laugh the most like a coyote?", games: ["Coyote"]),
    Rule(rule: "Who has the biggest shoes?", games: ["H2Olland"]),
    Rule(rule: "Who is the oldest?", games: ["Settlers of Catan (Beginner's version)", "Citadels", "Bohnanza", "Village"]),
    Rule(rule: "Who can hum the highest note?", games: ["Humm Bug"]),
    Rule(rule: "Who is the most like a Viking?", games: ["Fire & Axe: A Viking Saga"]),
    Rule(rule: "Who has the longest mustache?", games: ["Asterix and Obelix"]),
    Rule(rule: "Who has been to the most European countries?", games: ["Ticket to Ride: Europe"]),
    Rule(rule: "Who has the most money?", games: ["Alhambra"]),
    Rule(rule: "Who has the huskiest voice?", games: ["Snow Tails"]),
    Rule(rule: "Who looks the most like a goblin?", games: ["Kragmortha"]),
    Rule(rule: "Who was the last person to eat pineapple?", games: ["Tiki Topple"]),
    Rule(rule: "Who has most recently ridden on a magic carpet?", games: ["1001 Karawane"]),
    Rule(rule: "Who has the biggest sombrero?", games: ["Time's Up!"]),
    Rule(rule: "Who can give the best polar bear impression?", games: ["Ice Flow"]),
    Rule(rule: "Who daydreams the most?", games: ["Pocket Rockets"]),
    Rule(rule: "Who can tell the most romantic love story?", games: ["Genji"]),
    Rule(rule: "Who is the youngest?", games: ["Parade", "Arkadia"]),
    Rule(rule: "Who has the most facial hair?", games: ["Dig In!"]),
    Rule(rule: "Who has traveled the furthest in the last year?", games: ["Vasco da Gama"]),
    Rule(rule: "Who most recently built something?", games: ["World Without End"]),
    Rule(rule: "Who has most recently visited Ireland?", games: ["Keltis"]),
    Rule(rule: "Who last fed a duck?", games: ["Duck, Duck, Bruce"]),
    Rule(rule: "Who most recently visited a farm?", games: ["Farmageddon"]),
    Rule(rule: "Who has spent the least time on planet Terra in the Sol system?", games: ["Eclipse"]),
    Rule(rule: "Who has the least hair?", games: ["Dweebies"]),
    Rule(rule: "Who can do the best mammoth impression?", games: ["Ouga Bouga"]),
    Rule(rule: "Who has most recently used a wok?", games: ["We Will Wok You"]),
    Rule(rule: "Who visited Hamburg most recently?", games: ["The Speicherstadt"]),
    Rule(rule: "Who looks most like an ant?", games: ["Myrmes"]),
    Rule(rule: "Who can name the most moons of Jupiter?", games: ["Exoplanets"]),
    Rule(rule: "Who most recently read a history book?", games: ["Troyes"]),
  ];
}
